<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.5</version>
	<relativePath/>
        </parent>

	<groupId>com.tml.AIP_POSITION_JDG_TRANS</groupId>
	<artifactId>aip-cer-position-jdg</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>AIP-CRM-POSITION-JDG</name>
	<description>Demo project for POSITION JDG</description>
	<properties>
		<java.version>1.8</java.version>
		<jboss.datagrid.version>7.2.0.Final-redhat-9</jboss.datagrid.version>
		<version.org.infinispan>8.5.0.Final-redhat-9</version.org.infinispan>
		<maven-surefire-plugin.version>2.19.1</maven-surefire-plugin.version>
		<fuse.version>7.3.1.fuse-731003-redhat-00003</fuse.version>
		<!--
		<maven-surefire-plugin.version>2.8-redhat-1</maven-surefire-plugin.version> -->
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven-compiler-plugin.version>3.6.0</maven-compiler-plugin.version>
		<spring-boot-maven-plugin.version>2.1.4.RELEASE-redhat-00001</spring-boot-maven-plugin.version>
		<maven-jar-plugin.version>3.1.2</maven-jar-plugin.version>
		<maven-deploy-plugin.version>2.7</maven-deploy-plugin.version>
		<!--  <infinispan.version>8.5.0.Final-redhat-9</infinispan.version> -->
		<infinispan.version>13.0.6.Final-redhat-00001</infinispan.version>
		<!-- <version.infinispan>12.1.7.Final-redhat-00001</version.infinispan> -->
	</properties>
	
	<packaging>war</packaging>


	<distributionManagement>
		<repository>
			<id>nexus</id>
			<url>
				https://nexus-cicd.api.tatamotors.com/repository/maven-releases/</url>
		</repository>
	</distributionManagement>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.infinispan</groupId>
				<artifactId>infinispan-bom</artifactId>
				<version>${infinispan.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- 	<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc6</artifactId>
			<version>11.2.0.3</version>
		</dependency> -->

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!--
		https://mvnrepository.com/artifact/org.infinispan.protostream/protostream -->
		<dependency>
			<groupId>org.infinispan.protostream</groupId>
			<artifactId>protostream</artifactId>
			<version>4.6.5.Final-redhat-00002</version>
		</dependency>


		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.1.44</version>
		</dependency>


		<!--  <dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-remote</artifactId>
		</dependency>   -->

		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-remote-query-client</artifactId>
			<version>${infinispan.version}</version>
		</dependency>

		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-query-dsl</artifactId>
			<version>${infinispan.version}</version>
		</dependency>

		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-client-hotrod</artifactId>
			<!--   <version>${infinispan.version}</version> -->
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>1.2.3</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.2.3</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-access</artifactId>
			<version>1.2.3</version>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>5.2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-spring-boot-starter-remote</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.infinispan/infinispan-bom -->

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot-maven-plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
