#logging.config=classpath:log4j2.xml
#DB Connection Details
#spring.datasource.driverClassName=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//172.24.29.81:1521/MPCD
#spring.datasource.username=FUSEJDG
#spring.datasource.password=FUSEJDG
#spring.jpa.show-sql=true

#spring.datasource.driverClassName: oracle.jdbc.OracleDriver
#spring.datasource.url: jdbc:oracle:thin:@172.24.47.127:1521:OTPSQA
#spring.datasource.username: cordysqatx
#spring.datasource.password: cordysqatx
#spring.jpa.show-sql=true

#spring.datasource.driverClassName: oracle.jdbc.OracleDriver
#spring.datasource.url: jdbc:oracle:thin:@172.31.14.100:1521:BOP4PRD
#spring.datasource.username: cordysprdtx
#spring.datasource.password: cordysprdtx
#spring.jpa.show-sql=true

#spring.datasource.driverClassName: oracle.jdbc.OracleDriver
#spring.datasource.url: jdbc:oracle:thin:@172.24.48.117:1521:TMLDEV
#spring.datasource.username: ESBPVDev
#spring.datasource.password: ESBPVDev@1
#spring.jpa.show-sql=true
#logging.config=classpath:log4j2.xml
#server.context-parameters.isLog4jAutoInitializationDisabled=false
#logging.level.com.tml.AIP_POSITION_JDG_TRANS=WARN
#infinispan.remote.server-list=192.168.0.107:11222
#infinispan.remote.marshaller=org.infinispan.commons.marshall.ProtoStreamMarshaller
#infinispan.remote.java-serial-allowlist=com.tml.AIP_POSITION_JDG_TRANS.*

# infinispan.client.hotrod.socket_timeout = 600000
# infinispan.client.hotrod.connect_timeout = 600000
# infinispan.client.hotrod.max_retries = 5
 #infinispan.client.hotrod.client_intelligence=BASIC
 
#infinispan.client.hotrod.server_list = 192.168.0.107:11222,192.168.0.117:11222
#infinispan.client.hotrod.server_list = 10.21.34.79:31222
infinispan.client.hotrod.server_list = example-infinispan-datagrid-project.apps.ocp4.ocp2.local
infinispan.client.hotrod.auth_username = developer
infinispan.client.hotrod.auth_password = NhXSxBfkLgxsBFWG
infinispan.client.hotrod.auth_realm = default
infinispan.client.hotrod.sasl_mechanism = SCRAM-SHA-512
 
#spring.profiles.active=jdg

#infinispan.client.hotrod.protocol_version = 2.5
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://10.21.34.116:5432/datagriddb
spring.datasource.username: datagrid
spring.datasource.password: root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8896
management.port=8884

## notice we use named parameters in the queries, eg :#name.
## A named query parameter must start with :#
## sql that
#jdg.selectAccountData=SELECT PRE.LATITUDE LATITUDE,PRE.LONGITUDE  LONGITUDE,div.name div_name,DIV.X_PREFER_PARTNER_ID X_PREFER_PARTNER_ID,DIV.PAR_ROW_ID PAR_ROW_ID,prtnr.name  partner_name  FROM SIEBEL.S_ORG_EXT DIV,SIEBEL.S_ORG_EXT PRE,SIEBEL.S_ORG_EXT org,SIEBEL.S_ORG_EXT prtnr WHERE div.PR_IMPLSVC_VNDR_ID = PRE.ROW_ID(+)   and div.par_divn_id = org.row_id   and div.x_prefer_partner_id = prtnr.row_id(+) and PRE.LATITUDE is not null and PRE.LONGITUDE  is not null

#jdg.selectAccountData=SELECT PRE.LATITUDE LATITUDE,PRE.LONGITUDE  LONGITUDE,div.name div_name,DIV.X_PREFER_PARTNER_ID X_PREFER_PARTNER_ID,DIV.PAR_ROW_ID PAR_ROW_ID,prtnr.name  partner_name  FROM S_ORG_EXT DIV,S_ORG_EXT PRE,S_ORG_EXT org,S_ORG_EXT prtnr WHERE div.PR_IMPLSVC_VNDR_ID = PRE.ROW_ID(+)   and div.par_divn_id = org.row_id   and div.x_prefer_partner_id = prtnr.row_id(+) and PRE.LATITUDE is not null and PRE.LONGITUDE  is not null

#jdg.selectAccountData=SELECT ud.user_id,ud.user_name,ud.email_id,ud.mobile_no,l.lab_name,b.book_name,b.author,b.price from user_details ud INNER JOIN lab_details l on ud.user_id = l.user_id INNER JOIN books_details b on l.lab_id = b.lab_id

#jdg.selectAccountData= SELECT A.ROW_ID postn_rowid,A.NAME postn_name,A.POSTN_TYPE_CD,A.OU_ID Div_rowid,A.X_PROD_LN_ID,C.NAME AS Div_Name,D.NAME AS Org_Name,A.BU_ID AS Org_id,B.PAR_PARTY_ID AS Parent_Postn_ID,  A.PR_EMP_ID AS DSalCRM_EMP_ID,E.FST_NAME AS DSalCRM_EMP_NAME,E.CELL_PH_NUM AS DSalCRM_CELL_PHONE,E.EMAIL_ADDR AS DSalCRM_EMAIL,F.LOGIN DSalCRM_login FROM SIEBEL.S_POSTN A ,SIEBEL.S_PARTY B,SIEBEL.S_ORG_EXT C,SIEBEL.S_BU D,SIEBEL.S_CONTACT E,SIEBEL.S_USER F WHERE A.PAR_ROW_ID = B.ROW_ID AND A.OU_ID=C.ROW_ID AND A.BU_ID=D.ROW_ID AND A.PR_EMP_ID = E.ROW_ID(+) AND A.PR_EMP_ID = F.ROW_ID(+) AND POSTN_TYPE_CD='DSalCRM'  

jdg.selectAccountData=SELECT latitude, longitude, div_name, x_prefer_partner_id, par_row_id, partner_name FROM S_ORG_EXT
#jdg.selectAccountData=select  ACCOUNT_CODE	AS	account_code, PREVIOUS_DOC_NO AS previous_doc_no, PREVIOUS_DOC_DATE AS previous_doc_date, INVC_TYPE_CD AS invc_type_cd, RATE AS rate	,ACCOUNT_NAME	AS	account_name	,BILL_FROM_STATE	AS	bill_from_state	,BILL_TO_STATE	AS	bill_to_state	,BU_ID	AS	bu_id	,CGST_ASSESSIBLE_AMOUNT	AS	cgst_assessible_amount	,CGST_CLASSIFICATION	AS	cgst_classification	,CGST_TAX_PERCENTAGE	AS	cgst_tax_percentage	,COMMENTS	AS	comments	,CREATED_DT	AS	created_dt	,CUSTOMER_CODE	AS	customer_code	,DEALER_CODE	AS	dealer_code	,DELIVERY_LOCATION	AS	delivery_location	,DESC_TEXT	AS	desc_text	,DISCOUNT	AS	discount	,DISPATCH_FROM_STATE	AS	dispatch_from_state	,DIVISION	AS	division	,FINAL_TCS_AMOUNT	AS	final_tcs_amount	,FIRST_NAME	AS	first_name	,FROM_ADDRESS1	AS	from_address1	,FROM_ADDRESS2	AS	from_address2	,FROM_PIN_CODE	AS	from_pin_code	,FROM_PLACE	AS	from_place	,FROM_SUPPLIER_NAME	AS	from_supplier_name	,GSTIN	AS	gstin	,GSTIN_OF_SUPPLIER	AS	gstin_of_supplier	,GSTIN_PARTY_TYPE	AS	gstin_party_type	,GSTIN_REGISTRATION_TYPE	AS	gstin_registration_type	,HSN	AS	hsn	,IGST_ASSESSIBLE_AMOUNT	AS	igst_assessible_amount	,IGST_CLASSIFICATION	AS	igst_classification	,IGST_TAX_PERCENTAGE	AS	igst_tax_percentage	,INVC_ID	AS	invc_id	,INVC_ITM_DTL_ID	AS	invc_itm_dtl_id	,INVOICE_CANCELLATION_DATE	AS	invoice_cancellation_date	,INVOICE_DATE	AS	invoice_date	,INVOICE_NO	AS	invoice_no	,INVOICE_STATUS	AS	invoice_status	,IRN	AS	irn	,IRN_DATE	AS	irn_date	,IRN_STATUS	AS	irn_status	,ITEM_DTL_AMT	AS	item_dtl_amt	,KERALA_FLOOD_CESS_ASSESSIBLE_AMOUNT	AS	kerala_flood_cess_assessible_amount	,KERALA_FLOOD_CESS_CLASSIFICATION	AS	kerala_flood_cess_classification	,LAST_NAME	AS	last_name	,LAST_UPD	AS	last_upd	,NET_AMOUNT	AS	net_amount	,NTA	AS	nta	,ORDER_NO	AS	order_no	,ORGANIZATIONS	AS	organizations	,OUTPUT_CGST	AS	output_cgst	,OUTPUT_IGST	AS	output_igst	,OUTPUT_KERALA_FLOOD_CESS	AS	output_kerala_flood_cess	,OUTPUT_SGST	AS	output_sgst	,OUTPUT_UTGST	AS	output_utgst	,PART	AS	part	,PART_DESC	AS	part_desc	,PLACE_OF_SUPPLY	AS	place_of_supply	,PRODUCT_CATEGORY	AS	product_category	,PRODUCT_DESCRIPTION	AS	product_description	,PRODUCT_NAME	AS	product_name	,QUANTITY	AS	quantity	,SGST_ASSESSIBLE_AMOUNT	AS	sgst_assessible_amount	,SGST_CLASSIFICATION	AS	sgst_classification	 ,SGST_TAX_PERCENTAGE	AS	sgst_tax_percentage	,SHIP_TO_STATE	AS	ship_to_state	,STATE_CODE	AS	state_code	,TAX_AMOUNT	AS	tax_amount	,TAX_CATEGORY	AS	tax_category	,TCS	AS	tcs	,TCS_ASSESSABLE_AMOUNT	AS	tcs_assessable_amount	,TODAY_DATE	AS	today_date	,TOTAL_INVOICE_VALUE	AS	total_invoice_value	,TO_ADDRESS1	AS	to_address1	,TO_ADDRESS2	AS	to_address2	,TO_PIN_CODE	AS	to_pin_code	,UOM	AS	uom	,UTGST_ASSESSIBLE_AMOUNT	AS	utgst_assessible_amount	,UTGST_CLASSIFICATION	AS	utgst_classification	,UTGST_TAX_PERCENTAGE	AS	utgst_tax_percentage	,VAT_CLASSIFICATION	AS	vat_classification	,WARE_HOUSE_ID	AS	ware_house_id	,WARE_HOUSE_NAME	AS	ware_house_name	from OTC_SALES_DETAILS
#jdg.selectAccountData=select  BILL_FROM_STATE	AS	bill_from_state, TAX_CATEGORY	AS	tax_category, PART_DESC	AS	part_desc, GSTIN_PARTY_TYPE	AS	gstin_party_type, GSTIN_REGISTRATION_TYPE	AS	gstin_registration_type from OTC_SALES_DETAILS

#jdg.selectAccountData=SELECT   PRE.LATITUDE LATITUDE,PRE.LONGITUDE LONGITUDE,div.name  div_name,DIV.X_PREFER_PARTNER_ID X_PREFER_PARTNER_ID,DIV.PAR_ROW_ID PAR_ROW_ID,prtnr.name  partner_name FROM   SIEBEL.S_ORG_EXT DIV,SIEBEL.S_ORG_EXT PRE ,SIEBEL.S_ORG_EXT org,SIEBEL.S_ORG_EXT prtnr WHERE   div.PR_IMPLSVC_VNDR_ID = PRE.ROW_ID(+)  and div.par_divn_id = org.row_id and div.x_prefer_partner_id = prtnr.row_id(+)  AND DIV.ROW_ID in ('1-1DLFECL','1-1-1DRI4C1','1-1EDFCU5')
#jdg.selectAccountData=SELECT   div.name div_name FROM   SIEBEL.S_ORG_EXT DIV,SIEBEL.S_ORG_EXT PRE ,SIEBEL.S_ORG_EXT org,SIEBEL.S_ORG_EXT prtnr WHERE   div.PR_IMPLSVC_VNDR_ID = PRE.ROW_ID(+)  and div.par_divn_id = org.row_id and div.x_prefer_partner_id = prtnr.row_id(+)  AND DIV.ROW_ID in ('1-1DLFECL','1-1-1DRI4C1','1-1EDFCU5')
#AND  DIV.ROW_ID ='%?1'

#JDG Connection Details
#jdg.hostname=192.168.188.141
#jdg.hostname=8.tcp.ngrok.io
#jdg.port=10301
jdg.hostname=example-infinispan-datagrid-project.apps.ocp4.ocp2.local
jdg.port=80
jdg.totalDays = 2
jdg.totalValue = 1

#jdg.username = myuser
#jdg.password = changeme





data.exception.message1=BlogAlreadyExists
data.exception.message2=Not Found/Empty
data.exception.message3=DataConnectivityisLost
data.exception.message4=You Entered key is wrong/empty ... Please Check!